"use client";
import { translate } from "@/src/languages";
import { CookieService, ECookieVariable } from "@/src/services";
import { ELocale } from "@/src/types";
import Link from "next/link";
import React from "react";

const page = () => {
    return (
        <>
            <section className="banner-section inner-banner coach contact">
                <div className="overlay">
                    <div className="banner-content">
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-8 col-md-10">
                                    <div className="main-content">
                                        <h2>{translate("PRIVACY POLICY")}</h2>
                                        <div className="breadcrumb-area">
                                            <nav aria-label="breadcrumb">
                                                <ol className="breadcrumb d-flex align-items-center">
                                                    <li className="breadcrumb-item">
                                                        <Link href="/">{translate("Home")}</Link>
                                                    </li>
                                                    <li className="breadcrumb-item">
                                                        <Link href="#">{translate("Pages")}</Link>
                                                    </li>
                                                    <li
                                                        className="breadcrumb-item active"
                                                        aria-current="page"
                                                    >
                                                        {translate("Privacy Policy")}
                                                    </li>
                                                </ol>
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* <!-- Banner Section end --> */}

            {/* <!-- Contact start --> */}
            <section className="about-us">
                <div className="container">
                    <div className="row">
                        <div className="col">
                            <div style={{padding: '48px 0', whiteSpace: 'pre-line'}} className="paragraph-content">
                                {(() => {
                                    let content;
                                    switch (CookieService.get(ECookieVariable.USER_LOCALE)) {
                                        case ELocale.VIETNAM: {
                                            content = `
                                                <h3>Chính Sách Bảo Mật</h3>

                                                <span style="font-size:18px;font-weight:600">1. QUYỀN RIÊNG TƯ</span>
                                                Chúng tôi cam kết bảo vệ thông tin cá nhân của bạn. Chúng tôi đã tạo ra Chính Sách Bảo Mật này để thông báo cho bạn biết chúng tôi thu thập thông tin gì khi bạn sử dụng dịch vụ của chúng tôi tại các trang web trực tuyến của chúng tôi (tổng hợp là 'Dịch vụ'), tại sao chúng tôi thu thập thông tin này và cách chúng tôi sử dụng thông tin đã thu thập.
                                                Vui lòng lưu ý rằng Chính Sách Bảo Mật này sẽ được đồng thuận giữa bạn và Bezon như được xác định trong Điều Khoản và Điều Kiện Sử Dụng ('Bezon', 'Chúng tôi' hoặc 'Của chúng tôi', tùy trường hợp).
                                                Chúng tôi có thể định kỳ thay đổi Chính Sách Bảo Mật này và sẽ thông báo cho bạn về những thay đổi này bằng cách đăng các điều khoản sửa đổi trên trang web trực tuyến của chúng tôi. Chúng tôi khuyên bạn nên xem lại Chính Sách Bảo Mật này định kỳ.
                                                
                                                <span style="font-size:18px;font-weight:600">2. THÔNG TIN ĐƯỢC THU THẬP</span>
                                                Chúng tôi coi thông tin có thể được sử dụng để xác định một cá nhân, bao gồm, nhưng không giới hạn, tên và họ, ngày tháng năm sinh, chi tiết ngân hàng/thanh toán, địa chỉ nhà cửa hoặc địa chỉ vật lý khác, địa chỉ email, số điện thoại hoặc thông tin liên hệ khác là Thông Tin Cá Nhân ('Thông Tin Cá Nhân'). Bạn có thể được yêu cầu cung cấp Thông Tin Cá Nhân khi bạn sử dụng trang web của chúng tôi, đăng ký tài khoản hoặc sử dụng Dịch Vụ. Thông Tin Cá Nhân chúng tôi thu thập có thể bao gồm thông tin như: thông tin liên hệ (bao gồm số điện thoại), thông tin giao hàng, thông tin thanh toán, lịch sử giao dịch, sở thích sử dụng trang web và phản hồi về Dịch Vụ. Ngoài ra, khi bạn tương tác với Dịch Vụ, máy chủ của chúng tôi lưu trữ một nhật ký hoạt động duy nhất dành riêng cho bạn, thu thập một số thông tin quản trị và thông tin lưu lượng bao gồm: địa chỉ IP nguồn, thời gian truy cập, ngày truy cập, trang web đã truy cập, ngôn ngữ sử dụng, báo cáo sự cố phần mềm và loại trình duyệt đã sử dụng. Thông tin này là quan trọng để cung cấp và đảm bảo chất lượng của Dịch Vụ. Chúng tôi không thu thập Thông Tin Cá Nhân về bạn trên Dịch Vụ mà không có sự hiểu biết của bạn.
                                                
                                                <span style="font-size:18px;font-weight:600">3. CÁCH THỨC THU THẬP VÀ XỬ LÝ DỮ LIỆU</span>
                                                Chúng tôi có thể tự động thu thập một số dữ liệu cụ thể như đã thảo luận ở trên và nhận Thông Tin Cá Nhân về bạn khi bạn cung cấp thông tin đó thông qua Dịch Vụ hoặc thông qua các tương tác và trò chuyện khác với chúng tôi. Chúng tôi cũng có thể nhận Thông Tin Cá Nhân từ các nhà cung cấp trực tuyến và các nhà cung cấp dịch vụ đề xuất bạn đến các Trang web Nhãn Trắng và từ danh sách khách hàng mua hợp pháp từ các nhà cung cấp bên ngoài thứ ba. Ngoài ra, chúng tôi có thể sử dụng dịch vụ của các nhà cung cấp dịch vụ bên thứ ba để cung cấp hỗ trợ kỹ thuật, xử lý các giao dịch trực tuyến của bạn và duy trì tài khoản trực tuyến của bạn. Chúng tôi sẽ có quyền truy cập vào bất kỳ thông tin nào bạn cung cấp cho các nhà cung cấp, nhà cung cấp dịch vụ và dịch vụ thương mại điện tử bên thứ ba này, và chúng tôi sẽ sử dụng Thông Tin Cá Nhân như đã mô tả trong Chính Sách Bảo Mật này phía dưới. Thông tin này chỉ sẽ được tiết lộ cho các bên thứ ba ngoài Bezon theo đúng Chính Sách Bảo Mật này. Chúng tôi thực hiện các biện pháp để đảm bảo rằng các thỏa thuận của chúng tôi với các nhà cung cấp dịch vụ bên thứ ba và các nhà cung cấp trực tuyến bảo vệ quyền riêng tư của bạn.
                                                
                                                <span style="font-size:18px;font-weight:600">4. SỬ DỤNG THÔNG TIN</span>
                                                Chúng tôi sử dụng Thông Tin Cá Nhân mà chúng tôi thu thập từ bạn để cung cấp Dịch Vụ của chúng tôi, để cung cấp hỗ trợ khách hàng, thực hiện các kiểm tra bảo mật và xác minh danh tính cần thiết, xử lý bất kỳ giao dịch trực tuyến nào của bạn, đáp ứng các yêu cầu kinh doanh cụ thể và cho bất kỳ mục đích nào liên quan đến việc vận hành Dịch Vụ. Thông Tin Cá Nhân của bạn cũng có thể được chúng tôi sử dụng để cung cấp cho bạn các ưu đãi quảng cáo và thông tin về sản phẩm và dịch vụ của Bezon, cũng như để Bezon có thể cung cấp một loạt sản phẩm và dịch vụ và cải thiện dịch vụ khách hàng. Thỉnh thoảng, chúng tôi có thể yêu cầu thông tin từ bạn thông qua cuộc khảo sát hoặc cuộc thi. Việc tham gia vào những cuộc khảo sát hoặc cuộc thi này là hoàn toàn tự nguyện, và do đó, bạn có quyền lựa chọn có hay không tiết lộ thông tin như vậy. Thông tin được yêu cầu có thể bao gồm thông tin liên hệ (như tên, địa chỉ thư tín và số điện thoại), và thông tin về đối tượng (như mã zip hoặc mã bưu điện hoặc tuổi). Nếu bạn chọn tham gia vào một cuộc khảo sát hoặc cuộc thi và trúng thưởng, bằng việc chấp nhận bất kỳ giải thưởng cuộc thi hoặc thắng cược từ chúng tôi, bạn đồng ý sử dụng tên và hình ảnh của bạn cho mục đích quảng cáo và khuyến mãi mà không cần thêm bất kỳ khoản bồi thường nào, trừ khi bị cấm bởi luật pháp. Trừ khi bạn đã chọn không nhận thông tin quảng cáo, chúng tôi cũng có thể sử dụng Thông Tin Cá Nhân của bạn (bao gồm địa chỉ email và số điện thoại) để cung cấp thông tin về sản phẩm, dịch vụ và khuyến mãi của chúng tôi, bao gồm các sản phẩm trò chơi khác (bao gồm dịch vụ sòng bạc trực tuyến, sòng bạc trực tiếp, bingo, poker, dịch vụ sáng tạo và sản phẩm và dịch vụ từ bên thứ ba được chúng tôi lựa chọn cẩn thận.
                                                
                                                <span style="font-size:18px;font-weight:600">5. MỘT SỐ THÔNG BÁO LOẠI TRỪ</span>
                                                Chúng tôi có thể tiết lộ Thông Tin Cá Nhân của bạn nếu phải làm như vậy theo luật pháp, hoặc nếu chúng tôi tin tưởng một cách tốt đẹp rằng việc hành động như vậy là cần thiết để: (1) tuân thủ bất kỳ quy trình pháp lý nào được phục vụ cho chúng tôi, bất kỳ trang web của chúng tôi hoặc Dịch Vụ hoặc trong trường hợp chúng tôi phải tuân thủ một nghĩa vụ pháp lý tương tự; (2) bảo vệ và bào vệ quyền của chúng tôi hoặc tài sản; hoặc (3) hành động để bảo vệ sự an toàn cá nhân của người dùng của Dịch Vụ hoặc công chúng. Nếu, theo quyết định duy nhất của chúng tôi, bạn được xem là đã gian lận hoặc cố gắng lừa dối chúng tôi, hoặc bất kỳ người dùng khác của Dịch Vụ theo bất kỳ cách nào, bao gồm nhưng không giới hạn việc điều khiển trò chơi hoặc gian lận thanh toán, hoặc nếu chúng tôi nghi ngờ bạn thực hiện thanh toán gian lận, bao gồm việc sử dụng tài khoản ngân hàng bị đánh cắp, hoặc bất kỳ hoạt động gian lận nào khác (bao gồm bất kỳ giao dịch hoàn trả hoặc đảo ngược thanh toán nào khác) hoặc giao dịch bị cấm (bao gồm rửa tiền), chúng tôi có quyền chia sẻ thông tin này (kèm theo danh tính của bạn) với các trang web trò chơi trực tuyến khác, ngân hàng, công ty thẻ tín dụng và các cơ quan thích hợp khác.
                                                
                                                <span style="font-size:18px;font-weight:600">6. QUYỀN TRUY CẬP</span>
                                                Bạn có thể 'từ chối' nhận bất kỳ thông tin quảng cáo nào, bằng cách chọn tùy chọn từ chối khi tùy chọn như vậy được cung cấp trên trang web của chúng tôi hoặc trong Dịch Vụ hoặc tin nhắn SMS bạn nhận được từ chúng tôi, hoặc bất kỳ lúc nào bạn có thể liên hệ trực tiếp với Dịch Vụ Hỗ trợ Trò chuyện 24/7 của chúng tôi trên trang web Bezon của chúng tôi. Ngoài ra, bạn có thể liên hệ với chúng tôi thông qua Dịch Vụ Hỗ trợ Trò chuyện 24/7 của chúng tôi và chúng tôi có thể sắp xếp cuộc gọi video nếu bạn: 1) muốn xác nhận tính chính xác của Thông Tin Cá Nhân chúng tôi đã thu thập về bạn; 2) muốn cập nhật Thông Tin Cá Nhân của bạn hoặc xóa Thông Tin Cá Nhân của bạn; và/hoặc 3) có bất kỳ khiếu nại nào liên quan đến việc chúng tôi sử dụng Thông Tin Cá Nhân của bạn. Nếu được yêu cầu, chúng tôi sẽ thay đổi mọi thông tin bạn đã cung cấp cho chúng tôi hoặc đánh dấu bất kỳ thông tin nào để ngăn chặn việc sử dụng trong tương lai, miễn là bạn cung cấp bằng chứng theo yêu cầu của chúng tôi một cách hợp lý cho những thay đổi đó.
                                                
                                                <span style="font-size:18px;font-weight:600">7. SỰ ĐỒNG Ý SỬ DỤNG CÁC NHÀ CUNG CẤP DỊCH VỤ ĐIỆN TỬ</span>
                                                Để chơi các trò chơi bằng tiền thật trên Dịch Vụ, bạn sẽ phải gửi tiền cho chúng tôi và nhận tiền từ chúng tôi. Chúng tôi có thể sử dụng các nhà xử lý thanh toán điện tử bên thứ ba và/hoặc các tổ chức tài chính ('ESPs' như Ví điện tử và Ngân hàng trực tuyến) để xử lý các giao dịch tài chính như vậy. Bằng việc chấp nhận Chính Sách Bảo Mật này, bạn đồng ý rõ ràng rằng Thông Tin Cá Nhân cần thiết cho việc xử lý các giao dịch sẽ được chia sẻ với ESPs, bao gồm cả việc chuyển thông tin ra ngoài quốc gia của bạn khi cần thiết. Chúng tôi thực hiện các biện pháp để đảm bảo rằng các thỏa thuận của chúng tôi với ESPs bảo vệ quyền riêng tư của bạn.
                                                
                                                <span style="font-size:18px;font-weight:600">8. SỰ ĐỒNG Ý VỚI VIỆC XEM XÉT BẢO MẬT</span>
                                                Chúng tôi có quyền thực hiện xem xét bảo mật bất kỳ lúc nào để xác thực danh tính của bạn, tuổi của bạn, dữ liệu đăng ký mà bạn cung cấp và xác minh việc bạn sử dụng Dịch Vụ và các giao dịch tài chính của bạn có vi phạm Điều Khoản và Điều Kiện của chúng tôi và luật pháp áp dụng không. Bằng việc chấp nhận Điều Khoản và Điều Kiện của chúng tôi, bạn ủy quyền cho chúng tôi, nhân viên của chúng tôi, đại diện và nhà cung cấp sử dụng Thông Tin Cá Nhân của bạn và tiết lộ Thông Tin Cá Nhân của bạn cho bên thứ ba để xác thực thông tin bạn cung cấp cho chúng tôi trong quá trình sử dụng Dịch Vụ. Xem xét bảo mật có thể bao gồm nhưng không giới hạn việc đặt hàng báo cáo ngân hàng hoặc thanh toán và/hoặc xác minh thông tin bạn cung cấp so với cơ sở dữ liệu của bên thứ ba. Ngoài ra, để hỗ trợ các xem xét bảo mật này, bạn đồng ý cung cấp thông tin hoặc tài liệu mà chúng tôi có thể yêu cầu.
                                                
                                                <span style="font-size:18px;font-weight:600">9. SỰ ĐỒNG Ý VỚI VIỆC SỬ DỤNG PHẦN MỀM CHỐNG GIAN LẬN</span>
                                                Gói phần mềm của chúng tôi - được sử dụng để truy cập và sử dụng Dịch Vụ - chứa một số tính năng được thiết kế để phát hiện việc sử dụng các chương trình tự động hóa cho phép trí tuệ nhân tạo (không phải con người) chơi trên trang web của chúng tôi. Việc sử dụng các chương trình phần mềm bot như vậy vi phạm Điều Khoản và Điều Kiện của chúng tôi, khi chúng tôi xem xét nó là có hại đối với các người chơi khác. Bằng cách cài đặt phần mềm của chúng tôi và sử dụng Dịch Vụ, bạn đồng ý với việc phần mềm của chúng tôi thực hiện các chức năng được mô tả trong phần này. Phần mềm của chúng tôi có thể thực hiện bất kỳ hoặc tất cả các chức năng sau đây để phát hiện việc sử dụng các chương trình tự động hóa trái phép và đảm bảo rằng chúng tôi duy trì môi trường 'không gian lận' cho tất cả người chơi: (1) quét danh sách các ứng dụng phần mềm hoạt động của bạn trong khi bạn sử dụng Dịch Vụ; (2) quét danh sách các tiến trình hoạt động của bạn trong khi bạn sử dụng Dịch Vụ; và (3) quét các tệp trong các thư mục liên quan đến trang web Dịch Vụ của bạn để đảm bảo rằng chỉ có các phiên bản 'không bị hack' của phần mềm của chúng tôi đang được sử dụng. Nếu bất kỳ quá trình nào được đề cập trước đó tiết lộ một ứng dụng hoặc tiến trình đáng nghi, phần mềm của chúng tôi có thể quét các tệp liên quan đến ứng dụng hoặc tiến trình đáng nghi và tổng hợp một mạng lưới tổng hợp (tức là một hồ sơ mô tả các tệp liên quan đến ứng dụng hoặc tiến trình) để so sánh với các hồ sơ của các chương trình tự động hóa trái phép đã biết. Phần mềm của chúng tôi sẽ không thực hiện bất kỳ tìm kiếm ngẫu nhiên nào trong phần lớn ổ cứng, thiết bị hoặc tệp của bạn và nó sẽ không truyền bất kỳ thông tin nào cho chúng tôi hoặc bất kỳ bên thứ ba nào khác ngoài thông tin cần thiết để xác định việc sử dụng các chương trình tự động hóa trái phép như đã mô tả ở trên. Phần mềm của chúng tôi sẽ không thay đổi bất kỳ tệp hoặc thông tin nào trên máy tính hoặc thiết bị của bạn và sẽ không can thiệp vào hoạt động của bất kỳ ứng dụng nào của bạn. Bạn có thể chấm dứt việc sử dụng phần mềm của chúng tôi bất kỳ lúc nào bằng cách gỡ cài đặt gói phần mềm của chúng tôi.
                                                
                                                <span style="font-size:18px;font-weight:600">10. BẢO MẬT</span>
                                                Chúng tôi hiểu rõ sự quan trọng của bảo mật thông tin và các kỹ thuật cần thiết để bảo vệ thông tin. Chúng tôi lưu trữ tất cả Thông Tin Cá Nhân chúng tôi nhận trực tiếp từ bạn trong một cơ sở dữ liệu được bảo mật bằng mật khẩu nằm trong mạng bảo mật của chúng tôi và được đặt sau phần mềm tường lửa tiên tiến đang hoạt động. Các trang web trực tuyến của chúng tôi và Dịch Vụ hỗ trợ giao thức SSL/TLS mới nhất. Chúng tôi thực hiện các biện pháp để đảm bảo rằng các công ty con của chúng tôi, đại lý, liên kết và nhà cung cấp cũng sử dụng mức độ bảo mật đủ đáng.
                                                
                                                <span style="font-size:18px;font-weight:600">11. BẢO VỆ TRẺ EM</span>
                                                Dịch Vụ không dành cho hoặc dành riêng cho những người dưới 21 tuổi. Bất kỳ người nào cung cấp thông tin của họ cho chúng tôi thông qua bất kỳ phần nào của Dịch Vụ đều đại diện cho chúng tôi rằng họ đã đủ 21 tuổi trở lên. Chính sách của chúng tôi là để phát hiện những nỗ lực của người dưới tuổi để truy cập Dịch Vụ của chúng tôi, điều này có thể đòi hỏi chúng tôi phải truy cập và xác minh Thông Tin Cá Nhân của bạn. Nếu chúng tôi nhận thấy rằng một người dưới tuổi đã cố gắng hoặc đã gửi thông tin cá nhân thông qua trang web trực tuyến, chúng tôi sẽ không chấp nhận thông tin này và sẽ thực hiện các biện pháp để loại bỏ thông tin đó khỏi hồ sơ của chúng tôi.
                                                
                                                <span style="font-size:18px;font-weight:600">12. TUYÊN BỐ PHÁP LÝ</span>
                                                Dịch Vụ hoạt động "TƯƠNG TỰ VỚI NHƯ VẬY" và "CÓ SẴN," mà không có bất kỳ trách nhiệm nào. Chúng tôi không chịu trách nhiệm cho các sự kiện ngoài tầm kiểm soát trực tiếp của chúng tôi. Bởi vì tính phức tạp và thay đổi liên tục của công nghệ và kinh doanh của chúng tôi, chúng tôi không thể đảm bảo và cũng không đại diện rằng sẽ có hiệu suất không có lỗi đối với quyền riêng tư của Thông Tin Cá Nhân của bạn, và chúng tôi sẽ không chịu trách nhiệm đối với bất kỳ thiệt hại gián tiếp, tình cờ, kết quả hoặc trừng phạt nào liên quan đến việc sử dụng hoặc tiết lộ Thông Tin Cá Nhân.
                                                
                                                <span style="font-size:18px;font-weight:600">13. SÁP NHẬP VÀ CÁC SỰ KIỆN KHÁC YÊU CẦU CHUYỂN</span>
                                                Nếu chúng tôi bao giờ phải đệ đơn xin phá sản, hoặc trở nên vô khả năng thanh toán, hoặc bị một bên thứ ba thâu tóm, sáp nhập với một bên thứ ba, bán toàn bộ hoặc một phần tài sản của chúng tôi, hoặc chuyển toàn bộ hoặc một phần đáng kể của các tài sản có liên quan của chúng tôi cho một bên thứ ba, chúng tôi có quyền chia sẻ Thông Tin Cá Nhân và tất cả thông tin khác bạn đã cung cấp thông qua Dịch Vụ cho các đối tác kinh doanh và sáp nhập tiềm năng và sau này.
                                                
                                                <span style="font-size:18px;font-weight:600">14. SỰ ĐỒNG Ý VỚI CHÍNH SÁCH BẢO MẬT</span>
                                                Bằng cách nhấp vào 'Tôi đồng ý' trong quá trình đăng ký hoặc bằng cách tiếp tục sử dụng Dịch Vụ sau khi Điều khoản Bảo mật này được đăng (nếu áp dụng), bạn đồng ý với Chính Sách Bảo Mật này. Đây là Chính Sách Bảo Mật toàn bộ và duy nhất của chúng tôi và nó thay thế bất kỳ phiên bản trước đây nào. Chính Sách Bảo Mật này nên được đọc cùng với Điều Khoản và Điều Kiện của chúng tôi và bất kỳ điều khoản bổ sung nào áp dụng được đăng trên trang web trực tuyến của chúng tôi. Chúng tôi có thể định kỳ thay đổi Chính Sách Bảo Mật này và sẽ thông báo cho bạn về những thay đổi này bằng cách đăng các điều khoản đã được sửa đổi trên trang web trực tuyến của chúng tôi. Chúng tôi khuyến nghị bạn kiểm tra lại Chính Sách Bảo Mật này một cách đều đặn.
                                            `;
                                            break;
                                        }
                                        case ELocale.KOREAN: {
                                            content = `
                                                <h3>개인정보 보호 정책</h3>

                                                <span style="font-size:18px;font-weight:600">1. 개인정보 보호</span>
                                                우리는 귀하의 개인 정보를 보호하기 위해 최선을 다하고 있습니다. 우리는 이 개인 정보 보호 정책을 만들었습니다. 이 정책은 귀하가 우리의 온라인 사이트(통칭 '서비스')를 이용할 때 우리가 어떤 정보를 수집하고, 왜 이 정보를 수집하는지, 그리고 수집한 정보를 어떻게 사용하는지를 알려드리기 위한 것입니다.
                                                이 개인 정보 보호 정책은 이용 약관('Bezon', 'We', 'Us', 또는 'Our'로 정의됨)에 정의된대로 귀하와 Bezon 간에 합의된 것임을 유의하십시오.
                                                우리는 주기적으로 이 개인 정보 보호 정책을 변경할 수 있으며 변경 사항을 온라인 사이트에 수정된 약관을 게시함으로써 귀하에게 통지할 것입니다. 귀하께서 이 개인 정보 보호 정책을 정기적으로 다시 확인하시기를 권장합니다.
                                                
                                                <span style="font-size:18px;font-weight:600">2. 수집된 정보</span>
                                                개인을 식별할 수 있는 정보로서, 이름, 생년월일, 은행/결제 정보, 집 또는 다른 주소, 이메일 주소, 전화번호 또는 다른 연락처 정보를 포함하지만 이에 한정되지 않는 정보를 개인 정보('개인 정보')로 간주합니다. 당신이 우리 웹사이트를 이용하거나 계정을 등록하거나 서비스를 사용할 때 개인 정보를 제공하라고 요청 받을 수 있습니다. 우리가 수집하는 개인 정보에는 다음과 같은 정보가 포함될 수 있습니다: 연락 정보(전화번호 포함), 배송 정보, 결제 정보, 거래 기록, 웹사이트 사용 선호도 및 서비스에 대한 피드백을 포함합니다. 또한, 서비스와 상호 작용할 때, 당사의 서버는 당신을 위한 고유한 활동 로그를 유지합니다. 이 로그는 소스 IP 주소, 액세스 시간, 액세스 날짜, 방문한 웹 페이지, 언어 사용, 소프트웨어 충돌 보고 및 사용된 브라우저 유형을 수집하는데 필수적인 정보입니다. 우리는 귀하의 동의 없이 서비스에서 귀하에 대한 개인 정보를 수집하지 않습니다.
                                                
                                                <span style="font-size:18px;font-weight:600">3. 데이터 수집 및 처리 방법</span>
                                                우리는 위에서 논의한대로 특정 데이터를 자동으로 수집하고 귀하가 서비스 또는 다른 의사 소통 및 상호 작용을 통해 그러한 정보를 제공하는 경우 개인 정보를 받을 수 있습니다. 또한, 귀하를 White Label 사이트로 참조하는 온라인 판매자 및 서비스 제공업체로부터 개인 정보를 수신할 수도 있습니다. 더불어, 우리는 기술 지원을 제공하고 온라인 거래를 처리하며 온라인 계정을 관리하기 위해 제3자 서비스 제공업체의 서비스를 이용할 수 있습니다. 우리는 이러한 업체, 서비스 제공업체 및 제3자 전자 상거래 서비스에 제공하는 정보에 접근할 것이며 이 정보를 이 개인 정보 보호 정책에서 설명한 대로 사용할 것입니다. 이 정보는 본 개인 정보 보호 정책에 따라 Bezon 외부의 제3자에게만 공개될 것입니다. 우리는 제3자 서비스 제공업체 및 온라인 판매자와의 협정이 귀하의 개인 정보를 보호하도록 조치를 취합니다.
                                                
                                                <span style="font-size:18px;font-weight:600">4. 정보 사용</span>
                                                귀하로부터 수집한 개인 정보를 우리는 서비스 제공, 고객 지원 제공, 필요한 보안 및 식별 검증 절차 수행, 귀하의 온라인 거래 처리, 특정 비즈니스 요구 사항 충족 및 서비스 운영과 관련된 다른 목적으로 사용합니다. 귀하의 개인 정보는 또한 Bezon 제품 및 서비스에 대한 홍보 제안 및 정보를 제공하는 데 사용되며 Bezon이 다양한 제품 및 서비스를 개선하고 고객 서비스를 개선하는 데 도움이 됩니다. 때로는 귀하로부터 조사나 대회를 통해 정보를 요청할 수도 있습니다. 이러한 조사나 대회에 참여는 완전히 자발적이며, 따라서 이러한 정보를 공개할지 여부를 선택할 수 있습니다. 요청된 정보에는 연락처 정보(이름, 주소 및 전화 번호와 같은)와 인구 통계 정보(우편 번호 또는 나이와 같은)가 포함될 수 있습니다. 조사나 대회에 참여하고 우승하는 경우, 우리로부터 어떤 대회 상품이나 이익을 수령함으로써 법률로 금지되지 않는 한 광고 및 홍보 목적으로 귀하의 이름과 유사한 것을 사용하는 데 동의합니다. 홍보 정보를 받지 않도록 선택하지 않은 경우, 우리는 귀하의 개인 정보(이메일 주소 및 전화 번호를 포함하여)를 제품, 서비스 및 프로모션에 관한 정보를 제공하기 위해 사용할 수도 있으며, 이 정보에는 우리가 주의를 기울여 선택한 제3자의 게임 제품(온라인 카지노, 라이브 카지노, 빙고, 포커, 스포츠 북 및 일반 게임 서비스 포함) 및 제품 및 서비스가 포함될 수 있습니다.
                                                
                                                <span style="font-size:18px;font-weight:600">5. 특정 제외된 공개 사항</span>
                                                법률에 따라 개인 정보를 공개해야 하는 경우 또는 우리가 좋은 신념으로 그런 조치가 필요하다고 믿을 경우, 우리는 다음과 같은 상황에서 귀하의 개인 정보를 공개할 수 있습니다: (1) 우리, 우리의 사이트 또는 서비스에 제공된 법적 절차를 준수하거나 본질적으로 유사한 법적 의무 하에서; (2) 우리의 권리 또는 재산을 보호하고 방어하는 경우; 또는 (3) 서비스 사용자 또는 공중의 개인 안전을 보호하려는 경우. 당사의 단독 판단에 따르면 귀하가 어떤 방식으로든 우리나 서비스의 다른 사용자를 속여 또는 사기를 시도했거나 게임 조작 또는 결제 사기를 포함하여 사기 행위를 하거나, 우리가 귀하의 사기적인 결제(도난 은행 계좌 사용 포함) 또는 다른 사기 행위(결제 환불 또는 기타 결제의 반전 포함) 또는 금지된 거래(자금 세탁 포함)를 의심하는 경우, 우리는 이 정보(귀하의 신분과 함께)를 다른 온라인 게임 사이트, 은행, 신용 카드 회사 및 적절한 기관과 공유할 권리를 보유합니다.
                                                
                                                <span style="font-size:18px;font-weight:600">6. 접근</span>
                                                우리의 사이트나 서비스 또는 당사로부터 받은 SMS에서 제공하는 옵션을 통해 '수신 거부'를 선택함으로써 프로모션 통신을 받지 않도록 선택할 수 있습니다. 또한 당사의 Bezon 웹사이트에서 24/7 채팅 지원을 통해 언제든지 직접 저희에게 문의할 수 있습니다. 또한, 귀하가 다음과 같은 경우에는 저희에게 연락할 수 있으며 비디오 통화 일정을 예약할 수 있습니다: 1) 귀하에 관해 수집한 개인 정보의 정확성을 확인하려는 경우; 2) 귀하의 개인 정보를 업데이트하거나 삭제하려는 경우; 그리고/또는 3) 귀하의 개인 정보 사용에 대한 불만이 있는 경우. 요청하면 귀하가 제공한 정보를 수정하거나 향후 사용을 금지하기 위해 해당 정보를 표시할 것이며, 그러한 변경 사항에 대해 합리적으로 요구되는 증거를 제공하시기 바랍니다.
                                                
                                                <span style="font-size:18px;font-weight:600">7. 전자 서비스 제공업체 사용에 대한 동의</span>
                                                서비스에서 실제 돈을 사용하여 게임을 하려면 당사로부터 돈을 보내고 받아야 할 것입니다. 이러한 금융 거래를 처리하기 위해 우리는 제3자 전자 지불 처리 업체 및/또는 금융 기관('ESP'로서 전자 지갑 및 온라인 뱅킹 포함)를 사용할 수 있습니다. 본 개인 정보 보호 정책을 수락함으로써 귀하는 귀하의 국가 외부로 정보를 전송하기 위한 필요한 거래 처리를 위한 개인 정보가 ESP와 공유되는 것에 명시적으로 동의합니다. 우리는 ESP와의 협정이 귀하의 개인 정보를 보호하도록 조치를 취합니다.
                                                
                                                <span style="font-size:18px;font-weight:600">8. 보안 검토에 대한 동의</span>
                                                우리는 언제든지 귀하의 신분, 나이, 귀하가 제공한 등록 데이터의 유효성을 검증하고 서비스 이용과 금융 거래가 당사의 이용 약관과 관련 법률을 위반하지 않는지 확인하기 위해 보안 검토를 진행할 권리를 보유합니다. 당사의 이용 약관을 수락함으로써 당사, 당사 직원, 대리인 및 공급업체가 서비스 이용 과정에서 제공하는 정보를 유효성 검사 목적으로 사용하고 서비스 이용 과정에서 제공하는 정보를 제3자에게 공개할 권리를 부여합니다. 보안 검토에는 은행 또는 결제 보고서 주문 및/또는 제3자 데이터베이스와 제공한 정보를 검증하는 등 여러 내용이 포함될 수 있습니다. 또한 이러한 보안 검토를 용이하게 하기 위해 요구되는 정보 또는 문서를 제공하는 데 동의하시기 바랍니다.
                                                
                                                <span style="font-size:18px;font-weight:600">9. 합법적인 게임 소프트웨어 사용에 대한 동의</span>
                                                당사의 서비스에 액세스하고 사용하기 위해 사용되는 소프트웨어 패키지에는 인공 지능(비인간)이 게임을 하는 데 사용되는 자동화 프로그램 사용을 감지하기 위한 특정 기능이 포함되어 있습니다. 이러한 봇 소프트웨어 프로그램의 사용은 다른 플레이어에게 해를 끼친다고 판단되는 경우 당사의 이용 약관을 위반합니다. 당사의 소프트웨어를 설치하고 서비스를 사용함으로써 귀하는 이 섹션에서 설명된 기능을 수행하는 당사의 소프트웨어 사용에 동의합니다. 당사의 소프트웨어는 다음과 같은 기능 중 하나 또는 모두를 수행하여 불법 자동화 프로그램 사용을 감지하고 모든 사용자에게 '사기 없는' 환경을 유지하기 위해 다음과 같은 기능 중 하나 또는 모두를 수행할 수 있습니다: (1) 서비스를 사용하는 동안 활성 소프트웨어 응용 프로그램 목록을 스캔합니다; (2) 서비스를 사용하는 동안 활성 프로세스 목록을 스캔합니다; 및 (3) 당사 소프트웨어의 '해킹되지 않은' 버전만 사용되고 있는지 확인하기 위해 White Label 서비스 사이트 관련 프로그램 폴더의 파일을 스캔합니다. 위의 프로세스 중 하나라도 의심스러운 응용 프로그램 또는 프로세스를 나타내면 당사 소프트웨어는 해당 응용 프로그램 또는 프로세스와 관련된 파일을 스캔하고 알려진 불법 자동화 프로그램의 프로필과 일치시키기 위한 복합 매쉬(즉, 해당 응용 프로그램 또는 프로세스와 관련된 파일을 특성화하는 프로필)을 작성할 수 있습니다. 당사의 소프트웨어는 귀하의 하드 드라이브, 장비 또는 파일의 큰 부분에 대한 임의의 검색을 수행하지 않으며, 정보를 당사나 제3자에게 전송하지 않으며 불법 자동화 프로그램 사용을 식별하기 위해 위에서 설명한 정보 외에는 제공하지 않을 것입니다. 당사의 소프트웨어는 귀하의 컴퓨터나 장비의 파일이나 정보를 수정하지 않으며 귀하의 응용 프로그램의 작동에 간섭하지 않을 것입니다. 귀하는 우리의 소프트웨어 사용을 언제든지 당사 소프트웨어 패키지를 제거함으로써 종료할 수 있습니다.
                                                
                                                <span style="font-size:18px;font-weight:600">10. 보안</span>
                                                당사는 정보 보안의 중요성과 정보를 보호하기 위해 필요한 기술을 이해하고 있습니다. 귀하로부터 직접 받은 모든 개인 정보는 우리의 안전한 네트워크 내에 위치한 암호화된 데이터베이스에 저장됩니다. 당사의 온라인 사이트와 서비스는 최신 SSL/TLS 프로토콜을 지원합니다. 우리는 당사의 자회사, 대리인, 제휴사 및 공급업체도 적절한 수준의 보안을 사용하도록 하기 위해 조치를 취합니다.
                                                
                                                <span style="font-size:18px;font-weight:600">11. 어린이 보호</span>
                                                서비스는 21세 미만의 사람을 대상으로 하지 않으며 그런 목적으로 지시되지 않았습니다. 서비스의 어떤 부분을 통해 귀하의 정보를 제공하는 사람은 당사에게 그들이 21세 이상임을 나타내야 합니다. 미성년자가 온라인 사이트를 통해 개인 정보를 제출하려고 시도하거나 제출한 경우, 우리는 이 정보를 수용하지 않을 것이며 이러한 정보를 우리의 레코드에서 제거하기 위한 조치를 취할 것입니다.
                                                
                                                <span style="font-size:18px;font-weight:600">12. 법적 면책사항</span>
                                                서비스는 '있는 그대로' 및 '사용 가능한 그대로'로 제공되며 어떠한 종류의 책임도 없습니다. 우리는 우리의 직접적인 통제를 벗어난 사건에 대한 책임을 지지 않습니다. 우리의 기술과 비즈니스의 복잡하고 끊임없이 변화하는 특성 때문에 귀하의 개인 정보의 개인 정보 보호에 관한 오류 없는 성능이 보장될 수 없으며, 개인 정보의 사용 또는 공개와 관련된 간접적인, 부수적인, 결과적인 또는 처벌적인 손해에 대한 책임을 지지 않을 것입니다.
                                                
                                                <span style="font-size:18px;font-weight:600">13. 합병 및 기타 이전 사건</span>
                                                만약 우리가 파산 신청을 하거나 지불 불능 상태가 되거나 제3자에게 인수되거나 제3자와 합병하거나 우리의 자산 일부 또는 전부를 판매하거나 우리의 관련 자산 일부 또는 전부를 제3자에게 거의 전부 또는 전부 이전해야 할 경우, 우리는 귀하가 서비스를 통해 제공한 개인 정보 및 모든 다른 정보를 잠재적 및 이후의 사업 및 합병 파트너와 공유할 권리가 있습니다.
                                                
                                                <span style="font-size:18px;font-weight:600">14. 개인 정보 보호 정책에 대한 동의</span>
                                                등록 과정 중 '동의'를 클릭하거나 이 개인 정보 보호 정책의 게시 이후(해당 경우) 서비스의 계속적인 사용으로 인해 귀하는 이 개인 정보 보호 정책에 동의합니다. 이것이 우리의 전체적이고 독점적인 개인 정보 보호 정책이며, 이전 버전을 대체합니다. 이 개인 정보 보호 정책은 우리의 이용 약관과 함께 읽어야 하며 우리의 온라인 사이트에 게시된 추가적인 적용 가능한 조건과 함께 읽어야 합니다. 우리는 주기적으로 이 개인 정보 보호 정책을 변경할 수 있으며 이러한 변경 사항을 우리의 온라인 사이트에 수정된 약관을 게시함으로써 귀하에게 통지할 것입니다. 귀하가 이 개인 정보 보호 정책을 정기적으로 검토하도록 권장합니다.
                                            `;
                                            break;
                                        }
                                        case ELocale.MYANMAR: {
                                            content = `
                                                <h3>ကိုယ်ရေးအချက်အလက်မူဝါဒ</h3>

                                                <span style="font-size:18px;font-weight:600">1. ကိုယ်ရေးကိုယ်တာ</span>
                                                သင်၏ ကိုယ်ရေးကိုယ်တာ အချက်အလက်များကို ကာကွယ်ရန် ကျွန်ုပ်တို့ ကတိပြုပါသည်။ ကျွန်ုပ်တို့၏အွန်လိုင်းဝဘ်ဆိုက်များ (စုပေါင်းအားဖြင့် 'ဝန်ဆောင်မှု') တွင် ကျွန်ုပ်တို့၏ဝန်ဆောင်မှုများကို သင်အသုံးပြုသည့်အခါ ကျွန်ုပ်တို့စုဆောင်းရရှိသည့်အချက်အလက်များကို သင့်အား အသိပေးရန် ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို ဖန်တီးထားပါသည်။
                                                ဤကိုယ်ရေးကိုယ်တာမူဝါဒသည် သင်နှင့် Bezon အကြားအသုံးပြုမှုစည်းမျဉ်းစည်းကမ်းများ ('Bezon'၊ 'ကျွန်ုပ်တို့'၊ 'ကျွန်ုပ်တို့၏' သို့မဟုတ် 'ကျွန်ုပ်တို့၏'၊ အလျဉ်းသင့်သလို) သဘောတူညီမည်ဖြစ်သည်။
                                                ကျွန်ုပ်တို့သည် ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို အခါအားလျော်စွာ အပြောင်းအလဲများ ပြုလုပ်နိုင်ပြီး ကျွန်ုပ်တို့၏ အွန်လိုင်းဆိုက်တွင် ပြုပြင်ထားသော စည်းကမ်းချက်များကို ပို့စ်တင်ခြင်းဖြင့် အဆိုပါပြောင်းလဲမှုများကို သင့်အား အသိပေးပါမည်။ ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို ပုံမှန်ပြန်လည်ကြည့်ရှုရန် ကျွန်ုပ်တို့အကြံပြုပါသည်။
                                                
                                                <span style="font-size:18px;font-weight:600">2. အချက်အလက်စုဆောင်း</span>
                                                အမည်နှင့် နောက်ဆုံးအမည်၊ မွေးသက္ကရာဇ်၊ ဘဏ်/ငွေပေးချေမှုအသေးစိတ်၊ အိမ် သို့မဟုတ် အခြားရုပ်ပိုင်းဆိုင်ရာလိပ်စာ၊ အီးမေးလ်လိပ်စာ၊ ဖုန်းနံပါတ် သို့မဟုတ် အခြားဆက်သွယ်ရန်အချက်အလက်များအပါအဝင် လူတစ်ဦးချင်းစီကို ခွဲခြားသတ်မှတ်ရန် အသုံးပြုနိုင်သည့် အချက်အလက်များကို ကျွန်ုပ်တို့ ထည့်သွင်းစဉ်းစားပါသည်။ ကိုယ်ရေးကိုယ်တာ အချက်အလက် ('ကိုယ်ရေးကိုယ်တာ အချက်အလက်')။ ကျွန်ုပ်တို့၏ဝဘ်ဆိုဒ်ကိုအသုံးပြုသည့်အခါ၊ အကောင့်တစ်ခုအတွက် စာရင်းသွင်းရန် သို့မဟုတ် ဝန်ဆောင်မှုကိုအသုံးပြုသည့်အခါတွင် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ပေးဆောင်ရန် တောင်းဆိုနိုင်ပါသည်။ ကျွန်ုပ်တို့စုဆောင်းထားသော ကိုယ်ရေးကိုယ်တာအချက်အလက်များတွင်- ဆက်သွယ်ရန်အချက်အလက် (တယ်လီဖုန်းနံပါတ်အပါအဝင်)၊ ပို့ဆောင်မှုအချက်အလက်၊ ငွေပေးချေမှုအချက်အလက်၊ ငွေပေးငွေယူမှတ်တမ်း၊ ဝဘ်ဆိုက်အသုံးပြုမှုဦးစားပေးများနှင့် ဝန်ဆောင်မှုနှင့်ပတ်သက်သော အကြံပြုချက်ကဲ့သို့သော အချက်အလက်များ ပါဝင်နိုင်ပါသည်။ ထို့အပြင်၊ သင်သည် ဝန်ဆောင်မှုနှင့် အပြန်အလှန် တုံ့ပြန်သည့်အခါ၊ ကျွန်ုပ်တို့၏ ဆာဗာများသည် စီမံခန့်ခွဲရေးနှင့် လမ်းကြောင်းဆိုင်ရာ အချက်အလက်အချို့ကို စုဆောင်းပေးသည့် လုပ်ဆောင်ချက်မှတ်တမ်းကို သင့်အတွက် သီးသန့်ထားရှိပေးသည်- အရင်းအမြစ် IP လိပ်စာ၊ ဝင်ရောက်အသုံးပြုချိန်၊ ဝင်ရောက်သည့်ရက်စွဲ၊ ဝင်ရောက်ခဲ့သည့် ဝဘ်စာမျက်နှာ(များ)၊ ဘာသာစကားအသုံးပြုမှု၊ ဆော့ဖ်ဝဲ ပျက်စီးမှု အစီရင်ခံစာများနှင့် အသုံးပြုသည့် ဘရောက်ဆာ အမျိုးအစား။ ဤအချက်အလက်သည် ဝန်ဆောင်မှု၏ ပံ့ပိုးမှုနှင့် အရည်အသွေးအတွက် မရှိမဖြစ်လိုအပ်ပါသည်။ ကျွန်ုပ်တို့သည် သင့်အသိပညာမရှိဘဲ ဝန်ဆောင်မှုတွင် သင့်နှင့်ပတ်သက်သော ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို မစုဆောင်းပါ။
                                                
                                                <span style="font-size:18px;font-weight:600">3. အချက်အလက်စုဆောင်းခြင်းနှင့် စီမံဆောင်ရွက်ခြင်းနည်းလမ်းများ</span>
                                                အထက်တွင် ဆွေးနွေးထားသည့်အတိုင်း ကျွန်ုပ်တို့သည် အချို့သော အချက်အလက်များကို အလိုအလျောက် စုဆောင်းနိုင်ပြီး ဝန်ဆောင်မှု သို့မဟုတ် ကျွန်ုပ်တို့နှင့် ကျွန်ုပ်တို့နှင့် အခြားဆက်သွယ်မှုများနှင့် အပြန်အလှန်ဆက်သွယ်မှုများမှတစ်ဆင့် ထိုကဲ့သို့သောအချက်အလက်များကို သင်ပေးဆောင်သည့် သင့်အကြောင်း ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို လက်ခံရရှိနိုင်ပါသည်။ ကျွန်ုပ်တို့သည် သင့်အား White Label Sites သို့ ရည်ညွှန်းသော အွန်လိုင်းရောင်းချသူများနှင့် ဝန်ဆောင်မှုပေးသူများထံမှ ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ရရှိနိုင်ပြီး ပြင်ပကုမ္ပဏီရောင်းချသူများထံမှ တရားဝင်ရရှိထားသော ဖောက်သည်စာရင်းများမှလည်း ရရှိနိုင်ပါသည်။ ထို့အပြင်၊ ကျွန်ုပ်တို့သည် နည်းပညာပံ့ပိုးမှု၊ သင်၏အွန်လိုင်းငွေပေးငွေယူများကို လုပ်ဆောင်ရန်နှင့် သင်၏အွန်လိုင်းအကောင့်ကို ထိန်းသိမ်းရန်အတွက် ပြင်ပမှဝန်ဆောင်မှုပေးသူများ၏ဝန်ဆောင်မှုများကို ချိတ်ဆက်နိုင်ပါသည်။ ထိုကဲ့သို့သော ရောင်းချသူများ၊ ဝန်ဆောင်မှုပေးသူများနှင့် ပြင်ပကုမ္ပဏီ e-commerce ဝန်ဆောင်မှုများကို သင်ပေးဆောင်သည့် မည်သည့်အချက်အလက်မဆို ကျွန်ုပ်တို့ထံ ဝင်ရောက်ခွင့်ရမည်ဖြစ်ပြီး၊ ဤကိုယ်ရေးကိုယ်တာမူဝါဒတွင် ဖော်ပြထားသည့်အတိုင်း ကျွန်ုပ်တို့သည် အောက်ဖော်ပြပါ ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို အသုံးပြုပါမည်။ ဤအချက်အလက်အား ဤကိုယ်ရေးကိုယ်တာမူဝါဒနှင့်အညီ Bezon ပြင်ပရှိ တတိယပုဂ္ဂိုလ်များအားသာ ထုတ်ဖော်ပါမည်။ ပြင်ပဝန်ဆောင်မှုပေးသူများနှင့် အွန်လိုင်းရောင်းချသူများနှင့် ကျွန်ုပ်တို့၏အစီအမံများသည် သင့်ကိုယ်ရေးကိုယ်တာလုံခြုံမှုကို ကာကွယ်ပေးကြောင်း သေချာစေရန်အတွက် ခြေလှမ်းများလုပ်ဆောင်ပါသည်။
                                                
                                                <span style="font-size:18px;font-weight:600">4. သတင်းအချက်အလက်အသုံးပြုမှု</span>
                                                ကျွန်ုပ်တို့သည် ကျွန်ုပ်တို့၏ဝန်ဆောင်မှုကိုပေးအပ်ရန်၊ သင့်ထံမှစုဆောင်းရရှိထားသော ဖောက်သည်ပံ့ပိုးမှုပေးရန်၊ လိုအပ်သောလုံခြုံရေးနှင့် အတည်ပြုစစ်ဆေးမှုများကို ဖော်ထုတ်ရန်၊ သင်၏အွန်လိုင်းငွေပေးငွေယူများကိုလုပ်ဆောင်ရန်၊ အချို့သောစီးပွားရေးလိုအပ်ချက်များနှင့်ပြည့်မီရန်နှင့် လုပ်ငန်းလည်ပတ်မှုနှင့်ပတ်သက်သည့် အခြားရည်ရွယ်ချက်များအတွက် ဝန်ဆောင်မှု။ Bezon ထုတ်ကုန်များနှင့် ဝန်ဆောင်မှုများနှင့်ပတ်သက်သော ပရိုမိုးရှင်းကမ်းလှမ်းမှုများနှင့် အချက်အလက်များကို သင့်အား ပေးဆောင်ရန်နှင့် Bezon မှ ထုတ်ကုန်များနှင့် ဝန်ဆောင်မှုများစွာကို ပိုမိုကောင်းမွန်စွာ ပံ့ပိုးပေးနိုင်ရန်နှင့် ပိုမိုကောင်းမွန်သော ဖောက်သည်ဝန်ဆောင်မှုများကို ပေးစွမ်းရန်အတွက် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကိုလည်း ကျွန်ုပ်တို့မှ အသုံးပြုနိုင်ပါသည်။ ရံဖန်ရံခါ၊ ကျွန်ုပ်တို့သည် စစ်တမ်းများ သို့မဟုတ် ပြိုင်ပွဲများမှတစ်ဆင့် သင့်ထံမှ အချက်အလက်များကို တောင်းဆိုနိုင်ပါသည်။ ဤစစ်တမ်းများ သို့မဟုတ် ပြိုင်ပွဲများတွင် ပါဝင်ခြင်းမှာ လုံးဝဆန္ဒအလျောက်ဖြစ်ပြီး၊ ထို့ကြောင့်၊ ထိုအချက်အလက်များကို ထုတ်ဖော်ခြင်းရှိ၊မရှိကို သင့်တွင် ရွေးချယ်ခွင့်ရှိသည်။ တောင်းဆိုထားသည့်အချက်အလက်များတွင် ဆက်သွယ်ရန်အချက်အလက် (အမည်၊ စာပေးစာယူလိပ်စာနှင့် တယ်လီဖုန်းနံပါတ်ကဲ့သို့) နှင့် လူဦးရေစာရင်းအချက်အလက် (ဇစ် သို့မဟုတ် စာတိုက်ကုဒ် သို့မဟုတ် အသက်ကဲ့သို့) ပါဝင်နိုင်သည်။ အကယ်၍ သင်သည် စစ်တမ်း သို့မဟုတ် ပြိုင်ပွဲတွင် ပါဝင်ရန် ရွေးချယ်ပြီး အနိုင်ရရှိပါက၊ ကျွန်ုပ်တို့ထံမှ မည်သည့်ပြိုင်ပွဲဆု သို့မဟုတ် အနိုင်ရမှုများကို လက်ခံခြင်းဖြင့်၊ ဥပဒေအရ တားမြစ်ထားသော အပိုလျော်ကြေးငွေမှလွဲ၍ ကြော်ငြာနှင့် ပရိုမိုးရှင်းရည်ရွယ်ချက်များအတွက် သင့်အမည်နှင့် ပုံသဏ္ဍာန်ကို အသုံးပြုရန် သဘောတူပါသည်။ ပရိုမိုးရှင်းအချက်အလက်များကို သင်လက်ခံရယူရန် ရွေးချယ်ခြင်းမရှိပါက၊ ကျွန်ုပ်တို့သည် သင့်အား ကျွန်ုပ်တို့၏ထုတ်ကုန်များ၊ ဝန်ဆောင်မှုများနှင့် ပရိုမိုးရှင်းများအကြောင်း အချက်အလက်များကို ပေးဆောင်ရန်အတွက် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များ (အီးမေးလ်လိပ်စာနှင့် ဖုန်းနံပါတ် အပါအဝင်) ကို အသုံးပြုနိုင်ပါသည်။ ဘင်ဂို၊ ဖဲချပ်၊ အားကစားစာအုပ် နှင့် ပေါ့ပေါ့ပါးပါးဂိမ်းဝန်ဆောင်မှုများ) နှင့် ကျွန်ုပ်တို့မှ ဂရုတစိုက်ရွေးချယ်ထားသော တတိယအဖွဲ့အစည်းများမှ ထုတ်ကုန်များနှင့် ဝန်ဆောင်မှုများ။

                                                <span style="font-size:18px;font-weight:600">5. အချို့သော ထုတ်ဖော်ပြောဆိုမှုများ မပါဝင်ပါ။</span>
                                                ဥပဒေအရ လိုအပ်ပါက ကျွန်ုပ်တို့သည် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ထုတ်ဖော်နိုင်သည်၊ သို့မဟုတ် ထိုသို့လုပ်ဆောင်ရန် လိုအပ်သည်ဟု ကျွန်ုပ်တို့ ယုံကြည်ပါက- (၁) ကျွန်ုပ်တို့တွင် ဆောင်ရွက်ပေးထားသည့် မည်သည့်ဥပဒေကြောင်းကိုမဆို လိုက်နာရန်၊ ကျွန်ုပ်တို့၏ဆိုက်များ သို့မဟုတ် ဝန်ဆောင်မှု သို့မဟုတ် အခြေအနေအရ၊ ကျွန်ုပ်တို့သည် သိသိသာသာ အလားတူတရားဝင်တာဝန်တစ်ရပ်အောက်တွင် ရှိနေပါသည်။ (၂) ကျွန်ုပ်တို့၏အခွင့်အရေးများ သို့မဟုတ် ပစ္စည်းဥစ္စာများကို ကာကွယ်ကာကွယ်ပေးခြင်း၊ သို့မဟုတ် (၃) ဝန်ဆောင်မှု သို့မဟုတ် အများသူငှာ အသုံးပြုသူများ၏ ကိုယ်ရေးကိုယ်တာ လုံခြုံရေးကို ကာကွယ်ရန် ဆောင်ရွက်ပါ။ ကျွန်ုပ်တို့၏ တစ်ခုတည်းသော ဆုံးဖြတ်ချက်တွင် သင်သည် ကျွန်ုပ်တို့အား လှည့်စားခြင်း သို့မဟုတ် လိမ်လည်လှည့်ဖြားရန် ကြိုးပမ်းခြင်း သို့မဟုတ် ဂိမ်းကစားခြင်း သို့မဟုတ် ငွေပေးချေမှုတွင် အကန့်အသတ်မရှိ အကန့်အသတ်မရှိ အပါအဝင် အခြားမည်သည့်နည်းဖြင့် ကျွန်ုပ်တို့ကို လိမ်လည်လှည့်ဖြားရန် ကြိုးပမ်းခဲ့သည် သို့မဟုတ် လိမ်လည်မှုအပါအဝင် သင့်အား လိမ်လည်သည့်ငွေပေးချေမှုဟု ကျွန်ုပ်တို့သံသယရှိပါက၊ ခိုးယူထားသော ဘဏ်အကောင့်များကို အသုံးပြုခြင်း သို့မဟုတ် အခြားသော လိမ်လည်လှည့်ဖြားသည့် လုပ်ဆောင်ချက် (ငွေပြန်အမ်းခြင်း သို့မဟုတ် ငွေပေးချေမှု၏ အခြားပြောင်းပြန်လှန်ခြင်း အပါအဝင်) သို့မဟုတ် တားမြစ်ထားသော ငွေပေးငွေယူ (ငွေခဝါချခြင်းအပါအဝင်)၊ ဤအချက်အလက်များကို အခြားအွန်လိုင်းဂိမ်းဆိုက်များနှင့် မျှဝေပိုင်ခွင့် (သင့်အထောက်အထားဖြင့်) မျှဝေပိုင်ခွင့်ကို ကျွန်ုပ်တို့ သိမ်းဆည်းထားပါသည်။ ဘဏ်များ၊ အကြွေးဝယ်ကတ်ကုမ္ပဏီများနှင့် သင့်လျော်သောအေဂျင်စီများ။
                                                
                                                <span style="font-size:18px;font-weight:600">6. ဝင်ရောက်ခွင့်</span>
                                                ကျွန်ုပ်တို့၏ဝဘ်ဆိုက်များ သို့မဟုတ် ကျွန်ုပ်တို့ထံမှ သင်လက်ခံရရှိသည့်ဝန်ဆောင်မှု သို့မဟုတ် SMS သို့မဟုတ် ကျွန်ုပ်တို့၏ 24/7 Chat Support ကို တိုက်ရိုက်စကားပြောခြင်းဖြင့် မည်သည့်အချိန်တွင်မဆို ပရိုမိုးရှင်းဆက်သွယ်ရေးကို လက်ခံရရှိခြင်းမှ ဖယ်ထုတ်ခြင်းအား ရွေးချယ်ခြင်းဖြင့်သော်လည်းကောင်း သင်သည် 'ဖယ်' နိုင်ပါသည်။ ကျွန်ုပ်တို့၏ Bezon ဝက်ဘ်ဆိုက်။ ထို့အပြင်၊ သင်သည် ကျွန်ုပ်တို့၏ 24/7 Chat Support မှတစ်ဆင့် ကျွန်ုပ်တို့ထံ ဆက်သွယ်နိုင်ပြီး အကယ်၍ သင်သည် ဗီဒီယိုခေါ်ဆိုမှုတစ်ခုကို အချိန်ဇယားဆွဲနိုင်သည်- 1) ကျွန်ုပ်တို့စုဆောင်းထားသော ကိုယ်ရေးကိုယ်တာအချက်အလက်များ၏ တိကျမှုကို အတည်ပြုလိုပါက၊ 2) သင်၏ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို အပ်ဒိတ်လုပ်လိုသည် သို့မဟုတ် သင်၏ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ဖျက်ပစ်လိုသည် ။ နှင့်/သို့မဟုတ် 3) သင်၏ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ကျွန်ုပ်တို့အသုံးပြုခြင်းနှင့် ပတ်သက်၍ တိုင်ကြားချက်တစ်စုံတစ်ရာ ရှိသည်။ တောင်းဆိုလာပါက၊ ကျွန်ုပ်တို့ထံ ပေးအပ်ထားသော အချက်အလက်မှန်သမျှကို ကျွန်ုပ်တို့ပြောင်းလဲပစ်မည် သို့မဟုတ် နောင်တွင်အသုံးပြုမှုကို တားမြစ်ရန် အချက်အလက်တစ်ခုခုကို အမှတ်အသားပြုမည်ဖြစ်ပြီး၊ ထိုသို့သောပြောင်းလဲမှုများအတွက် ကျွန်ုပ်တို့သည် ကျိုးကြောင်းဆီလျော်စွာ တောင်းဆိုနိုင်သောကြောင့် သက်သေအထောက်အထားများ ပေးစွမ်းနိုင်စေပါသည်။

                                                <span style="font-size:18px;font-weight:600">7. အီလက်ထရွန်းနစ် ဝန်ဆောင်မှုပေးသူများကို အသုံးပြုရန် သဘောတူညီချက်</span>
                                                ဝန်ဆောင်မှုတွင် ငွေအစစ်အမှန်ဂိမ်းများကို ကစားရန်အတွက်၊ သင်သည် ကျွန်ုပ်တို့ထံ ငွေပေးပို့ရန်နှင့် ငွေလက်ခံရန် လိုအပ်မည်ဖြစ်ပါသည်။ ထိုကဲ့သို့သော ငွေကြေးလွှဲပြောင်းမှုများကို လုပ်ဆောင်ရန်အတွက် ပြင်ပမှ အီလက်ထရွန်နစ်ငွေပေးချေမှု ပရိုဆက်ဆာများနှင့်/သို့မဟုတ် ဘဏ္ဍာရေးအဖွဲ့အစည်းများ ('ESPs' ကို e-Wallets နှင့် Online Banking အဖြစ်) အသုံးပြုနိုင်ပါသည်။ ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို လက်ခံခြင်းဖြင့်၊ သင်သည် လိုအပ်ပါက၊ လိုအပ်ပါက၊ သင့်နိုင်ငံပြင်ပတွင် သတင်းအချက်အလက်လွှဲပြောင်းခြင်းအပါအဝင် ESPs နှင့် မျှဝေထားသော ငွေပေးငွေယူများ လုပ်ဆောင်ရန်အတွက် လိုအပ်သော ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ရှင်းရှင်းလင်းလင်းသဘောတူပါသည်။ ESPs နှင့် ကျွန်ုပ်တို့၏အစီအစဥ်များသည် သင့်ကိုယ်ရေးကိုယ်တာလုံခြုံမှုကို ကာကွယ်ပေးကြောင်း သေချာစေရန်အတွက် ခြေလှမ်းများလုပ်ဆောင်ပါသည်။
                                                
                                                <span style="font-size:18px;font-weight:600">8. လုံခြုံရေးပြန်လည်သုံးသပ်ရန် သဘောတူချက်</span>
                                                သင်၏ အထောက်အထား၊ အသက်၊ မှတ်ပုံတင်ခြင်း အချက်အလက်တို့ကို အတည်ပြုရန်နှင့် ကျွန်ုပ်တို့၏ စည်းမျဥ်းစည်းမျဥ်းများနှင့် တည်ဆဲဥပဒေများကို ချိုးဖောက်နိုင်ခြေရှိသော ဝန်ဆောင်မှုကို ချိုးဖောက်မှုအတွက် သင်၏ဘဏ္ဍာရေးဆိုင်ရာ လွှဲပြောင်းမှုများကို အတည်ပြုရန် အချိန်မရွေး လုံခြုံရေးပြန်လည်သုံးသပ်မှုပြုလုပ်ရန် ကျွန်ုပ်တို့၏အခွင့်အရေးကို အာမခံပါသည်။ ကျွန်ုပ်တို့၏ စည်းမျဥ်းစည်းကမ်းများကို လက်ခံခြင်းဖြင့် သင်သည် ကျွန်ုပ်တို့၊ ကျွန်ုပ်တို့၊ ကျွန်ုပ်တို့၏ ဝန်ထမ်းများ၊ အေးဂျင့်များနှင့် ပေးသွင်းသူများသည် သင့်ကိုယ်ရေးကိုယ်တာ အချက်အလက်ကို အသုံးပြုရန်နှင့် ဝန်ဆောင်မှုများကို အသုံးပြုနေစဉ်အတွင်း ကျွန်ုပ်တို့အား ပေးဆောင်ထားသည့် အချက်အလက်များကို တရားဝင်ကြောင်းအတည်ပြုရန်အတွက် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ပြင်ပအဖွဲ့အစည်းများအား ထုတ်ဖော်ရန် သင့်အား ခွင့်ပြုထားပါသည်။ လုံခြုံရေး သုံးသပ်ချက်များတွင် ဘဏ်တစ်ခု သို့မဟုတ် ငွေပေးချေမှု အစီရင်ခံစာကို မှာယူခြင်းနှင့်/သို့မဟုတ် အခြားပြင်ပကုမ္ပဏီဒေတာဘေ့စ်များနှင့် ဆန့်ကျင်သည့် အချက်အလက်များအား စစ်ဆေးခြင်းတွင် အကန့်အသတ်မရှိ ပါဝင်နိုင်သည်။ ထို့အပြင်၊ ဤလုံခြုံရေးသုံးသပ်ချက်များကို လွယ်ကူချောမွေ့စေရန်၊ ကျွန်ုပ်တို့တောင်းဆိုနိုင်သည်အတိုင်း အဆိုပါအချက်အလက်များ သို့မဟုတ် စာရွက်စာတမ်းများကို ပေးဆောင်ရန် သင်သဘောတူပါသည်။

                                                <span style="font-size:18px;font-weight:600">9. လှည့်စားမှုတိုက်ဖျက်ရေးဆော့ဖ်ဝဲကို အသုံးပြုရန် သဘောတူညီချက်</span>
                                                ကျွန်ုပ်တို့၏ ဆော့ဖ်ဝဲလ်ပက်ကေ့ချ် - ဝန်ဆောင်မှုကို ဝင်ရောက်အသုံးပြုရာတွင် အသုံးပြုသည် - ကျွန်ုပ်တို့၏ဆိုက်တွင် ကစားရန် အတု (လူမဟုတ်သော) ဉာဏ်ရည်ကို ဖွင့်ပေးနိုင်သည့် အလိုအလျောက်ပရိုဂရမ်များအသုံးပြုမှုကို သိရှိနိုင်ရန် ဒီဇိုင်းထုတ်ထားသည့် အင်္ဂါရပ်အချို့ပါရှိသည်။ ထိုကဲ့သို့သော ဘော့တ်ဆော့ဖ်ဝဲပရိုဂရမ်များကို အသုံးပြုခြင်းသည် ကျွန်ုပ်တို့၏ စည်းမျဥ်းစည်းကမ်းများကို ချိုးဖောက်ရာရောက်သည်၊ ၎င်းသည် အခြားကစားသမားများအတွက် အန္တရာယ်ဖြစ်စေသည်ဟု ကျွန်ုပ်တို့ယူဆပါသည်။ ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲကို ထည့်သွင်းပြီး ဝန်ဆောင်မှုကိုအသုံးပြုခြင်းဖြင့်၊ သင်သည် ဤကဏ္ဍတွင်ဖော်ပြထားသည့် လုပ်ဆောင်ချက်များကို လုပ်ဆောင်ပေးသည့် ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲကို သင်သဘောတူပါသည်။ ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲသည် တရားမဝင်သော အလိုအလျောက်စနစ်သုံး ပရိုဂရမ်များကို ထောက်လှမ်းသိရှိနိုင်စေရန်နှင့် သုံးစွဲသူအားလုံးအတွက် 'အလိမ်အညာ အခမဲ့' ပတ်ဝန်းကျင်ကို ထိန်းသိမ်းထားကြောင်း သေချာစေရန်အတွက် ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲသည် အောက်ပါလုပ်ဆောင်ချက်များကို လုပ်ဆောင်နိုင်သည်- (1) သင်အသုံးပြုနေစဉ်အတွင်း သင့်အသုံးပြုနေသည့် ဆော့ဖ်ဝဲအပလီကေးရှင်းများစာရင်းကို စကင်န်ဖတ်ပါ ဝန်ဆောင်မှု; (၂) ဝန်ဆောင်မှုကို သင်အသုံးပြုနေစဥ်အချိန်အတွင်း သင့်လုပ်ဆောင်နေသော လုပ်ငန်းစဉ်များစာရင်းကို စကင်န်ဖတ်ပါ။ နှင့် (၃) ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲလ်၏ 'hacked မဟုတ်သော' ဗားရှင်းများကိုသာ အသုံးပြုထားကြောင်း သေချာစေရန် သင်၏ White Label Service site-related program folders အတွင်းရှိ ဖိုင်များကို စကန်ဖတ်ပါ။ အထက်ဖော်ပြပါ လုပ်ငန်းစဉ်များထဲမှ သံသယအပလီကေးရှင်း သို့မဟုတ် လုပ်ငန်းစဉ်ကို ဖော်ပြပါက၊ ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲသည် သံသယအပလီကေးရှင်း သို့မဟုတ် လုပ်ငန်းစဉ်နှင့် ဆက်စပ်နေသော ဖိုင်များကို စကင်န်ဖတ်ကာ ပေါင်းစပ် mesh (ဆိုလိုသည်မှာ အပလီကေးရှင်း သို့မဟုတ် လုပ်ငန်းစဉ်နှင့် ဆက်စပ်နေသော ဖိုင်များကို ဖော်ပြသည့် ပရိုဖိုင်) ကို ကိုက်ညီစေရန် လုပ်ဆောင်နိုင်သည် လူသိများသော တရားမဝင် အလိုအလျောက် ပရိုဖိုင်များအတွက် ပရိုဖိုင်များကို ဆန့်ကျင်ခြင်း။ ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲလ်သည် သင့် hard drive၊ စက်ပစ္စည်း သို့မဟုတ် ဖိုင်များ၏ ကြီးမားသောအစိတ်အပိုင်းများကို ကျပန်းရှာဖွေမှုကို လုပ်ဆောင်မည်မဟုတ်ပါ၊ နှင့် အထက်တွင်ဖော်ပြထားသည့်တရားမဝင်အလိုအလျောက်စနစ်သုံးပရိုဂရမ်များအသုံးပြုမှုကိုခွဲခြားသတ်မှတ်ရန် လိုအပ်သောအချက်အလက်များမှလွဲ၍ ကျွန်ုပ်တို့ထံ သို့မဟုတ် အခြားမည်သည့်တတိယအဖွဲ့အစည်းကိုမဆို သတင်းပေးပို့မည်မဟုတ်ပါ။ ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲသည် သင့်ကွန်ပြူတာ သို့မဟုတ် အခြားစက်ပစ္စည်းရှိ မည်သည့်ဖိုင်များ သို့မဟုတ် အချက်အလက်ကိုမျှ ပြောင်းလဲမည်မဟုတ်သည့်အပြင် သင့်အက်ပ်ပလီကေးရှင်းများ၏လုပ်ဆောင်မှုကို အနှောင့်အယှက်ဖြစ်စေမည်မဟုတ်ပါ။ ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲလ်ပက်ကေ့ခ်ျကို ဖြုတ်လိုက်ခြင်းဖြင့် ကျွန်ုပ်တို့၏ဆော့ဖ်ဝဲလ်အသုံးပြုမှုကို အချိန်မရွေး ရပ်စဲနိုင်ပါသည်။
                                                
                                                <span style="font-size:18px;font-weight:600">10. လုံခြုံရေး</span>
                                                သတင်းအချက်အလက် လုံခြုံရေး၏ အရေးပါမှုနှင့် သတင်းအချက်အလက်ကို လုံခြုံစေရန် လိုအပ်သော နည်းပညာများကို ကျွန်ုပ်တို့ နားလည်ပါသည်။ ကျွန်ုပ်တို့သည် ကိုယ်ရေးကိုယ်တာအချက်အလက်အားလုံးကို သိမ်းဆည်းထားရာ ကျွန်ုပ်တို့သည် သင့်ထံမှ တိုက်ရိုက်လက်ခံရရှိသည့် စကားဝှက်ဖြင့် ကာကွယ်ထားသော ဒေတာဘေ့စ်အတွင်း အသက်ဝင်သော ခေတ်မီသော firewall software နောက်ကွယ်ရှိ ကျွန်ုပ်တို့၏ လုံခြုံသောကွန်ရက်အတွင်း နေထိုင်ပါသည်။ ကျွန်ုပ်တို့၏ အွန်လိုင်းဆိုက်များနှင့် ဝန်ဆောင်မှုသည် နောက်ဆုံးပေါ် SSL/TLS ပရိုတိုကောကို ပံ့ပိုးပေးပါသည်။ ကျွန်ုပ်တို့၏ လုပ်ငန်းခွဲများ၊ အေးဂျင့်များ၊ တွဲဖက်လုပ်ကိုင်သူများ နှင့် ပေးသွင်းသူများသည် လုံလောက်သော လုံခြုံရေးအဆင့်များကို အသုံးချကြောင်း သေချာစေရန်အတွက် ကျွန်ုပ်တို့ လုပ်ဆောင်ပါသည်။
                                                
                                                <span style="font-size:18px;font-weight:600">11. ကလေးများအား အကာအကွယ်ပေးခြင်း</span>
                                                ဝန်ဆောင်မှုသည် အသက် 21 နှစ်အောက် လူများအတွက် ရည်ရွယ်ခြင်း သို့မဟုတ် ညွှန်ကြားခြင်း မဟုတ်ပါ။ ဝန်ဆောင်မှု၏ တစ်စိတ်တစ်ပိုင်းမှတစ်ဆင့် ကျွန်ုပ်တို့ထံ ၎င်းတို့၏ အချက်အလက်များကို ပံ့ပိုးပေးသူ မည်သူမဆို ၎င်းတို့သည် အသက် 21 နှစ်နှင့် အထက်ဖြစ်ကြောင်း ကျွန်ုပ်တို့အား ကိုယ်စားပြုပါသည်။ သင်၏ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ဝင်ရောက်ကြည့်ရှုစစ်ဆေးရန် ကျွန်ုပ်တို့ပါဝင်နိုင်သည့် ကျွန်ုပ်တို့၏ဝန်ဆောင်မှုများကို ဝင်ရောက်ကြည့်ရှုရန် အရွယ်မရောက်သေးသူများ၏ကြိုးပမ်းမှုများကို ဖော်ထုတ်ရန် ကျွန်ုပ်တို့၏မူဝါဒဖြစ်သည်။ သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ဝင်ရောက်ကြည့်ရှုစစ်ဆေးရန် ကျွန်ုပ်တို့ပါဝင်နိုင်သည်။ အကယ်၍ အရွယ်မရောက်သေးသူတစ်ဦးသည် အွန်လိုင်းဆိုက်မှတစ်ဆင့် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို တင်သွင်းရန် ကြိုးပမ်းခဲ့သည် သို့မဟုတ် တင်သွင်းခဲ့ကြောင်း ကျွန်ုပ်တို့ သိရှိလာပါက၊ ကျွန်ုပ်တို့သည် ဤအချက်အလက်များကို လက်ခံမည်မဟုတ်သည့်အပြင် ကျွန်ုပ်တို့၏မှတ်တမ်းများမှ ထိုအချက်အလက်များကို ဖယ်ရှားရန် ခြေလှမ်းများလုပ်ဆောင်ပါမည်။
                                                
                                                <span style="font-size:18px;font-weight:600">12. ဥပဒေကြောင်းအရ ငြင်းဆိုချက်</span>
                                                ဝန်ဆောင်မှုသည် မည်သည့်အမျိုးအစားမှ တာဝန်ယူမှုမရှိဘဲ 'AS-IS' နှင့် 'AS-AVAILABLE' တို့ကို လုပ်ဆောင်ပါသည်။ ကျွန်ုပ်တို့၏ တိုက်ရိုက်ထိန်းချုပ်မှုထက် ကျော်လွန်သော အဖြစ်အပျက်များအတွက် ကျွန်ုပ်တို့တွင် တာဝန်မရှိပါ။ ကျွန်ုပ်တို့၏နည်းပညာနှင့် လုပ်ငန်း၏ ရှုပ်ထွေးပြီး အဆက်မပြတ်ပြောင်းလဲနေသော သဘာ၀ကြောင့်၊ သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များ၏ လျှို့ဝှက်ရေးဆိုင်ရာ အမှားအယွင်းကင်းသော စွမ်းဆောင်နိုင်မှုရှိကြောင်း ကျွန်ုပ်တို့က အာမခံနိုင်မည်မဟုတ်သလို ကျွန်ုပ်တို့သည် အာမခံချက်မပြုနိုင်သည့်အပြင်၊ သွယ်ဝိုက်သော၊ မတော်တဆဖြစ်မှု၊ နောက်ဆက်တွဲအကျိုးဆက်များအတွက် ကျွန်ုပ်တို့မှ တာဝန်ရှိမည်မဟုတ်ပါ။ သို့မဟုတ် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို အသုံးပြုခြင်း သို့မဟုတ် ထုတ်ပြန်ခြင်းနှင့်စပ်လျဉ်းသည့် ပြစ်ဒဏ်ပေးခြင်းများ။

                                                <span style="font-size:18px;font-weight:600">13. လွှဲပြောင်းမှုလိုအပ်သော ပေါင်းစည်းမှုများနှင့် အခြားဖြစ်ရပ်များ</span>
                                                အကယ်၍ ကျွန်ုပ်တို့သည် ဒေဝါလီခံရန် လျှောက်ထားသင့်သည်၊ သို့မဟုတ် ပျက်ပြားသွားပါက၊ သို့မဟုတ် ပြင်ပအဖွဲ့အစည်းမှ ရယူထားခြင်း၊ တတိယအဖွဲ့အစည်းနှင့် ပေါင်းစည်းရန်၊ ကျွန်ုပ်တို့၏ ပိုင်ဆိုင်မှုအားလုံး သို့မဟုတ် တစ်စိတ်တစ်ပိုင်းကို ရောင်းချခြင်း သို့မဟုတ် ကျွန်ုပ်တို့၏ သက်ဆိုင်ရာပိုင်ဆိုင်မှုများ၏ အစိတ်အပိုင်းအားလုံးကို သို့မဟုတ် အစိတ်အပိုင်းတစ်ခုအား ပြင်ပအဖွဲ့အစည်းထံ သိသိသာသာ လွှဲပြောင်းပေးမည်ဆိုပါက၊ ဝန်ဆောင်မှုမှတစ်ဆင့် သင်ပေးအပ်ထားသော ကိုယ်ရေးကိုယ်တာအချက်အလက်နှင့် အခြားအချက်အလက်များအားလုံးကို အလားအလာရှိသော၊ နောက်ဆက်တွဲစီးပွားရေးလုပ်ငန်းနှင့် ပေါင်းစည်းထားသည့် မိတ်ဖက်များထံသို့ မျှဝေခံစားခွင့်ရှိသည်။
                                                
                                                <span style="font-size:18px;font-weight:600">14. ကိုယ်ရေးကိုယ်တာမူဝါဒကို သဘောတူညီချက်ရယူပါ။</span>
                                                မှတ်ပုံတင်ခြင်းလုပ်ငန်းစဉ်အတွင်း 'ကျွန်ုပ်သဘောတူသည်' ကိုနှိပ်ခြင်းဖြင့် သို့မဟုတ် ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို တင်ပြီးနောက် (သက်ဆိုင်သည့်အတိုင်း) ဝန်ဆောင်မှုကို ဆက်လက်အသုံးပြုခြင်းဖြင့် သင်သည် ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို သဘောတူပါသည်။ ၎င်းသည် ကျွန်ုပ်တို့၏ သီးသန့်ကိုယ်ရေးကိုယ်တာမူဝါဒတစ်ခုလုံးဖြစ်ပြီး ၎င်းသည် မည်သည့်အစောပိုင်းဗားရှင်းကိုမဆို အစားထိုးထားသည်။ ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို ကျွန်ုပ်တို့၏ စည်းမျဥ်းစည်းကမ်းများနှင့် ကျွန်ုပ်တို့၏အွန်လိုင်းဝဘ်ဆိုက်များတွင် တင်ထားသော နောက်ထပ်သက်ဆိုင်သည့် စည်းမျဉ်းများနှင့် တွဲဖက်ဖတ်ရှုရပါမည်။ ကျွန်ုပ်တို့သည် ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို အခါအားလျော်စွာ အပြောင်းအလဲများ ပြုလုပ်နိုင်ပြီး ကျွန်ုပ်တို့၏ အွန်လိုင်းဆိုက်များတွင် ပြုပြင်ထားသော စည်းကမ်းချက်များကို ပို့စ်တင်ခြင်းဖြင့် အဆိုပါပြောင်းလဲမှုများကို သင့်အား အသိပေးပါမည်။ ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို ပုံမှန်ပြန်လည်ကြည့်ရှုရန် ကျွန်ုပ်တို့အကြံပြုပါသည်။
                                            `;
                                            break;
                                        }
                                        default: {
                                            content =`
                                                <h3>PRIVACY POLICY</h3>

                                                <span style="font-size:18px;font-weight:600">1. PRIVACY</span>
                                                We are committed to protecting your personal information. We have created this Privacy Policy to let you know what information We collect when you use Our services at Our online sites (collectively, the 'Service'), why We collect this information and how We use the collected information.
                                                Please note that this Privacy Policy will be agreed between you and the Bezon as defined in the Terms and Conditions of Use ('Bezon', 'We', 'Us' or 'Our', as appropriate).
                                                We may periodically make changes to this Privacy Policy and will notify you of these changes by posting the modified terms on Our online site. We recommend that you revisit this Privacy Policy regularly.

                                                <span style="font-size:18px;font-weight:600">2. INFORMATION COLLECTED</span>
                                                We consider information that may be used to identify an individual, including, but not limited to, first and last name, date of birth, bank/payment details, home or other physical address, email address, phone number or other contact information to be Personal Information ('Personal Information'). You may be asked to provide Personal Information when you use Our website, register for an account or to use the Service. The Personal Information that We collect may include information such as: contact information (including telephone number), shipping information, billing information, transaction history, website usage preferences, and feedback regarding the Service. In addition, when you interact with the Service, our servers keep an activity log unique to you that collects certain administrative and traffic information including: source IP address, time of access, date of access, web page(s) visited, language use, software crash reports and type of browser used. This information is essential for the provision and quality of the Service. We do not collect Personal Information about you on the Service without your knowledge. 

                                                <span style="font-size:18px;font-weight:600">3. MEANS OF COLLECTING AND PROCESSING DATA</span>
                                                We may automatically collect certain data as discussed above and receive Personal Information about you where you provide such information through the Service or other communications and interactions with Us. We may also receive Personal Information from online vendors and service providers that refer you to the White Label Sites, and from customer lists lawfully acquired from third-party vendors. In addition, we may engage the services of third-party service providers to provide technical support, process your online transactions and maintain your online account. We will have access to any information you provide to such vendors, service providers and third-party e-commerce services, and We will use the Personal Information as set out in this Privacy Policy below. This information will only be disclosed to third parties outside the Bezon in accordance with this Privacy Policy. We take steps to ensure that Our arrangements with third-party service providers and online vendors protect your privacy.

                                                <span style="font-size:18px;font-weight:600">4. INFORMATION USE</span>
                                                We use the Personal Information We collect from you to deliver Our Service, to provide customer support, to undertake necessary security and identify verification checks, to process any of your online transactions, meet certain business requirements and for any other purpose related to the operation of the Service. Your Personal Information may also be used by Us to provide you with promotional offers and information regarding Bezon products and services and in order for the Bezon to better provide a range of products and services and improved customer service. From time-to-time, we may request information from you via surveys or contests. Participation in these surveys or contests is completely voluntary, and, therefore, you have the choice of whether or not to disclose such information. Information requested may include contact information (such as name, correspondence address and telephone number), and demographic information (such as zip or postal code or age). If you choose to participate in a survey or contest and win, by accepting any contest prize or winnings from Us, you consent to use of your name and likeness for advertising and promotional purposes without additional compensation, except were prohibited by law. Unless you have elected not to receive promotional information, we may also use your Personal Information (including your email address and phone number) to provide you with information regarding our products, services and promotions, including other gaming products (including online casino, live casino, bingo, poker, sportsbook and casual games services) and products and services from third parties carefully selected by Us. 

                                                <span style="font-size:18px;font-weight:600">5. CERTAIN EXCLUDED DISCLOSURES</span>
                                                We may disclose your Personal Information if required to do so by law, or if We believe in good faith that such action is necessary to: (1) comply with any legal process served on Us, any of Our sites or the Service or in circumstances where We are under a substantially similar legal obligation; (2) protect and defend Our rights or property; or (3) act to protect the personal safety of users of the Service or the public. If, in Our sole determination, you are found to have cheated or attempted to defraud Us, or any other user of the Service in any way including but not limited to game manipulation or payment fraud, or if We suspect you of fraudulent payment, including use of stolen bank accounts, or any other fraudulent activity (including any chargeback or other reversal of a payment) or prohibited transaction (including money laundering), We reserve the right to share this information (together with your identity) with other online gaming sites, banks, credit card companies, and appropriate agencies. 

                                                <span style="font-size:18px;font-weight:600">6. ACCESS</span>
                                                You may 'opt out' of receiving any promotional communications either by choosing to opt out where such option is made available on Our sites or the Service or SMS you receive from Us, or at any time by chatting our 24/7 Chat Support directly in our Bezon website. In addition, you may contact Us via our 24/7 Chat Support and we can schedule a video call if you: 1) want to confirm the accuracy of the Personal Information We have collected about you; 2) would like to update your Personal Information or delete your Personal Information; and/or 3) have any complaint regarding Our use of your Personal Information. If requested, we will change any information you have provided to Us or mark any information to prohibit future use, provided that you provide evidence as We may reasonably require for such changes. 

                                                <span style="font-size:18px;font-weight:600">7. CONSENT TO USE OF ELECTRONIC SERVICE PROVIDERS</span>
                                                In order to play real money games on the Service, you will be required to send money to and receive money from Us. We may use third-party electronic payment processors and/or financial institutions ('ESPs' as e-Wallets and Online Banking) to process such financial transactions. By accepting this Privacy Policy, you expressly consent to Personal Information necessary for the processing of transactions being shared with ESPs, including, where necessary, the transfer of information outside of your country. We take steps to ensure that Our arrangements with ESPs protect your privacy. 

                                                <span style="font-size:18px;font-weight:600">8. CONSENT TO SECURITY REVIEW</span>
                                                We reserve the right to conduct a security review at any time to validate your identity, age, the registration data provided by you and to verify your use of the Service and your financial transactions for potential breach of Our Terms and Conditions and of applicable law. By accepting Our Terms and Conditions you authorize Us, Our staff, agents and suppliers to use your Personal Information and to disclose your Personal Information to third parties for the purposes of validating the information you provide to Us in the course of using the Services. Security reviews may include but are not limited to ordering a bank or payment report and/or otherwise verifying the information you provide against third-party databases. In addition, to facilitate these security reviews, you agree to provide such information or documentation as We may request.

                                                <span style="font-size:18px;font-weight:600">9. CONSENT TO USE OF ANTI-CHEATING SOFTWARE</span>
                                                Our software package - used to access and use the Service - contains certain features designed to detect use of automated programs that enable artificial (non-human) intelligence to play on Our site. Use of such bot software programs violates Our Terms and Conditions, where We deem it detrimental to other players. By installing Our software and using the Service, you consent to Our software performing the functions described in this section. Our software may perform any or all of the following functions in order to detect the use of illicit automated programs and ensure that We maintain a 'cheat free' environment for all users: (1) scan your list of active software applications while you are using the Service; (2) scan your list of active processes while you are using the service; and (3) scan the files in your White Label Service site-related program folders to ensure that only 'non-hacked' versions of Our software are being used. If any of the foregoing processes reveals a suspect application or process, our software may scan the files associated with the suspect application or process and compile a composite mesh (i.e., a profile that characterizes the files associated with the application or process) to be matched against profiles for known illicit automated programs. Our software will not perform any random search of large portions of your hard drive, equipment or files, and it will not transmit any information to Us or to any third party other than the information necessary to identify use of illicit automated programs as described above. Our software will not alter any files or information on your computer or other equipment and will not interfere with the operation of any of your applications. You may terminate use of Our software at any time by uninstalling the Our software package.

                                                <span style="font-size:18px;font-weight:600">10. SECURITY</span>
                                                We understand the importance of information security and the techniques needed to secure information. We store all of the Personal Information We receive directly from you in a password-protected database residing within Our secure network behind active state-of-the-art firewall software. Our online sites and the Service support latest SSL/TLS protocol. We take steps to ensure Our subsidiaries, agents, affiliates and suppliers also employ adequate levels of security. 

                                                <span style="font-size:18px;font-weight:600">11. PROTECTION OF CHILDREN</span>
                                                The Service is not intended for or directed at persons under the age of 21. Any person who provides their information to Us through any part of the Service represents to Us that they are 21 years of age or older. It is Our policy to uncover attempts by minors to access Our Services which may involve Us having to access and verify your Personal Information. This may involve Us having to access and verify your Personal Information. If We become aware that a minor has attempted to or has submitted personal information via the online site, we will not accept this information and will take steps to remove such information from Our records. 

                                                <span style="font-size:18px;font-weight:600">12. LEGAL DISCLAIMER</span>
                                                The Service operates 'AS-IS' and 'AS-AVAILABLE,' without liability of any kind. We are not responsible for events beyond Our direct control. Because of the complex and constantly changing nature of Our technology and business, we cannot guarantee nor do We represent that there will be error-free performance regarding the privacy of your Personal Information, and We will not be liable for any indirect, incidental, consequential or punitive damages relating to the use or release of Personal Information.

                                                <span style="font-size:18px;font-weight:600">13. MERGERS AND OTHER EVENTS REQUIRING TRANSFER</span>
                                                If We should ever file for bankruptcy, or become insolvent, or be acquired by a third party, merge with a third party, sell all or part of Our assets, or transfer substantially all or part of Our relevant assets to a third party, we are entitled to share the Personal Information and all other information you have provided through the Service to potential and subsequent business and merger partners.

                                                <span style="font-size:18px;font-weight:600">14. CONSENT TO PRIVACY POLICY</span>
                                                By clicking 'I agree' during the registration process or by your continued use of the Service following the posting of this Privacy Policy (as applicable), you agree to this Privacy Policy. This is Our entire and exclusive Privacy Policy and it supersedes any earlier version. This Privacy Policy should be read in conjunction with Our Terms and Conditions and any additional applicable terms posted on Our online sites. We may periodically make changes to this Privacy Policy and will notify you of these changes by posting the modified terms on Our online sites. We recommend that you revisit this Privacy Policy regularly.
                                            `;
                                        }
                                    }
                                    return <div dangerouslySetInnerHTML={{__html: content}}></div>
                                })()}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* <!-- Contact end --> */}
        </>
    );
};

export default page;